pro/todo/todo/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    url('^todoapp/', include('todoapp.urls')), #http://127.0.0.1:8000/todoapp/
]

pro/todo/todoapp/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path
from todoapp import views
from . import views

app_name = 'todoapp'

urlpatterns = [
    # path('admin/', admin.site.urls),
    url(r'^$', views.IndexView.as_view(),name='index'), #views.py, takes index function
    # todoappp/1
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(),name='detail'),#views.py, takes detail function

]

pro/todo/todoapp/models.py
from django.db import models

# Create your models here.

class Task(models.Model):
    
    def __str__(self):
        return self.task_name

    task_name = models.CharField(max_length=200)
    task_priority = models.CharField(max_length=200)

pro/todo/todoapp/views.py
from django.views import generic
from .models import Task

class IndexView(generic.ListView):
    template_name = 'todoapp/index.html'

    def get_queryset(self):
        return Task.objects.all()

class DetailView(generic.DetailView):
    model = Task
    template_name = 'todoapp/detail.html'

''' Old Views.py

from django.shortcuts import render
from django.http import HttpResponse, Http404
from .models import Task
from django.template import loader

# Create your views here.

def index(request):
    task_list = Task.objects.all() # Retrieve all the objects from the task model
    # template = loader.get_template('todoapp/index.html')
    context = {

        'task_list': task_list
    }
    #output = ','.join([q.task_name for q in task_list])# Retrieve all of the task_names in the task_list and append a comma after them
    return render(request, 'todoapp/index.html', context)

# Detail View
def detail(request, task_id): # Accepts task_id
    try:
        task = Task.objects.get(pk=task_id) # Filters out task to get requested
    except Task.DoesNotExist:
        raise Http404('Task does not exist')
    context = {
        'task': task,
    }
    return render(request, 'todoapp/detail.html', context) #Passes context into detail.html
'''

pro/todo/todoapp/templates/todoapp/base.html
{% load staticfiles %}
<html>
    <head>
            <link rel="stylesheet" type="text/css" href="{% static 'todoapp/style.css' %}">
            <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    </head>
    <body>
            <nav class="navbar navbar-dark bg-dark">
                    <div class="container-fluid">
                        <div class="navbar-header">
                            <a class= "navbar-brand" href="#">TodoApp</a>
                        </div>
                        <ul class="nav navbar-nav">
                            <li class="active"><a href="#">Item 1</a></li>
                            <li><a href="#">Item 2</a></li>
                        </ul>
                        <ul class="nav navbar-nav navbar-right">
                                <li class="active"><a href="#">Item 1</a></li>
                                <li><a href="#">Item 2</a></li>
                        </ul>
                    </div>
                </nav>

            {% block body %}
            {% endblock %}
    </body>
</html>

pro/todo/todoapp/templates/todoapp/detail.html
{% extends 'todoapp/base.html' %}

{% block body %}
{{task.task_name}}</br>
{{task.task_priority}}

{% endblock %}

pro/todo/todoapp/templates/todoapp/index.html
{% extends 'todoapp/base.html' %}
{% load staticfiles %}
<html>
    <head>
       
    </head>
    <body>
            {% block body %}
<!--
            {% if task_list %}
            <ul>
                {% for task in task_list %}
            <li>
                <a href="{% url 'todoapp:detail' task.id %}">{{task.task_name}}</a>
            </li>
                {% endfor %}
            </ul>
            {% else %}
            {% endif %}
-->

            <div class="container">
                <h2>Today's List</h2>
                <p>Let's get things done!</p>
                <table class="table">
                    <thead>
                        <tr>
                            <th>Task Name</th>
                            <th>Task Priority</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% if task_list %}
                        {% for task in object_list %}
                        <tr class="active">
                            <td><a href="{% url 'todoapp:detail' task.id %}">{{task.task_name}}</a> </td>
                            <td><b>{{task.task_priority}}</b></td>
                            <td><button type="submit" class="btn btn-success">Done</button></td>
                        </tr>
                        {% endfor %}
                        {% endif %}
                    </tbody>
                </table>
            </div>
            {% endblock %}
    </body>
</html>